version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - "JWT_SECRET=${JWT_SECRET}"
      - "DATABASE_DSN=postgres://postgres:postgres@postgres:5432/smartcampus?sslmode=disable"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "3000:80"

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: smartcampus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
